# Generated by Django 5.0.6 on 2024-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='upload_required',
            field=models.BooleanField(default=False),
        ),
    ]
