# Generated by Django 5.0.6 on 2024-06-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
