# Generated by Django 5.0.6 on 2024-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='due_by',
            field=models.DateTimeField(null=True),
        ),
    ]
