# Generated by Django 5.0.6 on 2024-06-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(null=True),
        ),
    ]
