# Generated by Django 5.0.6 on 2024-07-02 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0015_alter_lecturer_user_alter_student_user'),
        ('quiz', '0013_alter_answer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('choices', models.JSONField()),
                ('score', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
