# Generated by Django 5.0.7 on 2024-07-26 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('middle_name', models.CharField(blank=True, max_length=256, null=True)),
                ('position', models.CharField(choices=[('Prof.', ' Professor'), ('Ass. Prof', 'Associate Professor'), ('Lecturer', 'Lecturer'), ('Dr.', 'Doctor'), ('Ass. Lecturer', 'Assistant Lecturer')], max_length=21)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_title', models.CharField(max_length=256)),
                ('course_code', models.CharField(max_length=8, null=True)),
                ('credit_hours', models.IntegerField()),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.lecturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('middle_name', models.CharField(blank=True, max_length=256, null=True)),
                ('cummulative', models.DecimalField(decimal_places=2, default=4.0, editable=False, max_digits=3)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='coursestudents', to='home.student'),
        ),
    ]
