# Generated by Django 5.0.6 on 2024-06-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='position',
            field=models.CharField(choices=[('Prof', ' Professor '), ('Ass. Prof', 'Associate Professor'), ('Lecturer', 'Lecturer'), ('Dr.', 'Doctor'), ('Ass. Lecturer', 'Assistant Lecturer')], max_length=21),
        ),
    ]
