# Generated by Django 5.0.6 on 2024-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_lecturer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
