# Generated by Django 5.0.6 on 2024-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='position',
            field=models.CharField(choices=[('Professor', ' Prof. '), ('Associate Professor', 'Ass. Professor'), ('Lecturer', 'Lecturer'), ('Doctor', 'Dr.'), ('Assistant Lecturer', 'Ass. Lecturer')], max_length=21),
        ),
    ]
