# Generated by Django 5.0.6 on 2024-06-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_resource_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
